import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";

// Curated list of real-world GTIN-13 barcodes. Sourced from Open Food Facts —
// each is a well-known, publicly listed retail item. Used to bootstrap a
// retailer's catalogue with scannable products so QR / passport generation
// can be end-to-end tested without hand-typing barcodes.
const SAMPLE_GTINS: string[] = [
  "5449000000996", // Coca-Cola 330ml
  "5449000131805", // Coca-Cola Zero
  "5000112637939", // Coca-Cola Original
  "3017620422003", // Nutella 400g
  "5000159407236", // Snickers
  "5000159461122", // Mars bar
  "7622210449283", // Milka chocolate
  "8000500310427", // Kinder Bueno
  "5000112611861", // Fanta Orange
  "5000112614404", // Sprite
  "5410188006711", // Pringles Original
  "8076809513388", // Barilla Spaghetti n.5
  "8410076472052", // Colgate toothpaste
  "3560070462384", // Evian water
  "3068320055008", // Perrier
  "7613034626844", // Nescafé Gold
  "5000295142930", // Kellogg's Corn Flakes
  "5011321957008", // Heinz Ketchup
  "5060335630001", // Innocent smoothie
  "6001069000160", // Ouma Rusks (SA)
];

async function resolveRetailerId(supabase: any, userId: string): Promise<string | null> {
  const { data } = await supabase
    .from("user_roles")
    .select("retailer_id")
    .eq("user_id", userId)
    .not("retailer_id", "is", null)
    .limit(1)
    .maybeSingle();
  return data?.retailer_id ?? null;
}

async function fetchOff(gtin: string): Promise<{
  name: string;
  brand: string | null;
  image_url: string | null;
} | null> {
  try {
    const res = await fetch(
      `https://world.openfoodfacts.org/api/v2/product/${encodeURIComponent(gtin)}.json`,
      { headers: { "user-agent": "tag-app/1.0" } },
    );
    if (!res.ok) return null;
    const json: any = await res.json();
    if (json?.status !== 1 || !json.product) return null;
    const p = json.product;
    const name =
      p.product_name_en ||
      p.product_name ||
      p.generic_name_en ||
      p.generic_name ||
      `Product ${gtin}`;
    return {
      name: String(name).slice(0, 200),
      brand: p.brands ? String(p.brands).split(",")[0].trim().slice(0, 120) : null,
      image_url: p.image_front_url || p.image_url || null,
    };
  } catch {
    return null;
  }
}

export const seedSampleProducts = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .handler(async ({ context }) => {
    const { supabase, userId } = context;
    const retailerId = await resolveRetailerId(supabase, userId);
    if (!retailerId) throw new Error("No retailer");

    // Skip GTINs already tagged for this retailer.
    const { data: existing } = await supabase
      .from("products")
      .select("gtin")
      .eq("retailer_id", retailerId)
      .in("gtin", SAMPLE_GTINS);
    const have = new Set((existing ?? []).map((r: any) => r.gtin).filter(Boolean));

    let created = 0;
    let skipped = 0;
    let failed = 0;
    const productIds: string[] = [];

    for (const gtin of SAMPLE_GTINS) {
      if (have.has(gtin)) {
        skipped++;
        continue;
      }
      const off = await fetchOff(gtin);
      const name = off?.name ?? `Sample product ${gtin}`;
      const brand = off?.brand ?? null;
      const image_url = off?.image_url ?? null;

      const { data: ins, error } = await supabase
        .from("products")
        .insert({
          retailer_id: retailerId,
          sku: gtin,
          gtin,
          barcode_type: "GTIN-13",
          name,
          display_name: name,
          brand,
          image_url,
          thumbnail_url: image_url,
          price_cents: 1999,
          stock_qty: 25,
          low_stock_threshold: 5,
          created_by: userId,
        })
        .select("id, retailer_id")
        .single();

      if (error || !ins) {
        failed++;
        continue;
      }
      created++;
      productIds.push(ins.id);

      // Queue passport enrichment so QR + DPP are generated by the tick job.
      await supabase
        .from("passport_enrichment_queue")
        .upsert(
          { product_id: ins.id, retailer_id: ins.retailer_id },
          { onConflict: "product_id" },
        );
    }

    return { created, skipped, failed, total: SAMPLE_GTINS.length, productIds };
  });
