/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScanShortCodeRouteImport } from './routes/scan.$shortCode'
import { Route as NMessageIdRouteImport } from './routes/n.$messageId'
import { Route as AuthenticatedStoresRouteImport } from './routes/_authenticated/stores'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedQrTagsRouteImport } from './routes/_authenticated/qr-tags'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedIntentRouteImport } from './routes/_authenticated/intent'
import { Route as AuthenticatedIntelligenceRouteImport } from './routes/_authenticated/intelligence'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products.index'
import { Route as AuthenticatedNotificationsIndexRouteImport } from './routes/_authenticated/notifications.index'
import { Route as AuthenticatedProductsProductIdRouteImport } from './routes/_authenticated/products.$productId'
import { Route as AuthenticatedNotificationsNewRouteImport } from './routes/_authenticated/notifications.new'
import { Route as AuthenticatedNotificationsCampaignIdRouteImport } from './routes/_authenticated/notifications.$campaignId'
import { Route as ApiPublicScanInterestRouteImport } from './routes/api/public/scan.interest'
import { Route as ApiPublicSShortCodeRouteImport } from './routes/api/public/s.$shortCode'
import { Route as ApiPublicHooksNotificationsTickRouteImport } from './routes/api/public/hooks.notifications-tick'
import { Route as ApiPublicHooksIntentTickRouteImport } from './routes/api/public/hooks.intent-tick'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanShortCodeRoute = ScanShortCodeRouteImport.update({
  id: '/scan/$shortCode',
  path: '/scan/$shortCode',
  getParentRoute: () => rootRouteImport,
} as any)
const NMessageIdRoute = NMessageIdRouteImport.update({
  id: '/n/$messageId',
  path: '/n/$messageId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStoresRoute = AuthenticatedStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQrTagsRoute = AuthenticatedQrTagsRouteImport.update({
  id: '/qr-tags',
  path: '/qr-tags',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIntentRoute = AuthenticatedIntentRouteImport.update({
  id: '/intent',
  path: '/intent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntelligenceRoute =
  AuthenticatedIntelligenceRouteImport.update({
    id: '/intelligence',
    path: '/intelligence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProductsRoute,
  } as any)
const AuthenticatedNotificationsIndexRoute =
  AuthenticatedNotificationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedNotificationsRoute,
  } as any)
const AuthenticatedProductsProductIdRoute =
  AuthenticatedProductsProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => AuthenticatedProductsRoute,
  } as any)
const AuthenticatedNotificationsNewRoute =
  AuthenticatedNotificationsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedNotificationsRoute,
  } as any)
const AuthenticatedNotificationsCampaignIdRoute =
  AuthenticatedNotificationsCampaignIdRouteImport.update({
    id: '/$campaignId',
    path: '/$campaignId',
    getParentRoute: () => AuthenticatedNotificationsRoute,
  } as any)
const ApiPublicScanInterestRoute = ApiPublicScanInterestRouteImport.update({
  id: '/api/public/scan/interest',
  path: '/api/public/scan/interest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSShortCodeRoute = ApiPublicSShortCodeRouteImport.update({
  id: '/api/public/s/$shortCode',
  path: '/api/public/s/$shortCode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksNotificationsTickRoute =
  ApiPublicHooksNotificationsTickRouteImport.update({
    id: '/api/public/hooks/notifications-tick',
    path: '/api/public/hooks/notifications-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksIntentTickRoute =
  ApiPublicHooksIntentTickRouteImport.update({
    id: '/api/public/hooks/intent-tick',
    path: '/api/public/hooks/intent-tick',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/intelligence': typeof AuthenticatedIntelligenceRoute
  '/intent': typeof AuthenticatedIntentRoute
  '/notifications': typeof AuthenticatedNotificationsRouteWithChildren
  '/products': typeof AuthenticatedProductsRouteWithChildren
  '/qr-tags': typeof AuthenticatedQrTagsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/stores': typeof AuthenticatedStoresRoute
  '/n/$messageId': typeof NMessageIdRoute
  '/scan/$shortCode': typeof ScanShortCodeRoute
  '/notifications/$campaignId': typeof AuthenticatedNotificationsCampaignIdRoute
  '/notifications/new': typeof AuthenticatedNotificationsNewRoute
  '/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
  '/api/public/hooks/intent-tick': typeof ApiPublicHooksIntentTickRoute
  '/api/public/hooks/notifications-tick': typeof ApiPublicHooksNotificationsTickRoute
  '/api/public/s/$shortCode': typeof ApiPublicSShortCodeRoute
  '/api/public/scan/interest': typeof ApiPublicScanInterestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/intelligence': typeof AuthenticatedIntelligenceRoute
  '/intent': typeof AuthenticatedIntentRoute
  '/qr-tags': typeof AuthenticatedQrTagsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/stores': typeof AuthenticatedStoresRoute
  '/n/$messageId': typeof NMessageIdRoute
  '/scan/$shortCode': typeof ScanShortCodeRoute
  '/notifications/$campaignId': typeof AuthenticatedNotificationsCampaignIdRoute
  '/notifications/new': typeof AuthenticatedNotificationsNewRoute
  '/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/api/public/hooks/intent-tick': typeof ApiPublicHooksIntentTickRoute
  '/api/public/hooks/notifications-tick': typeof ApiPublicHooksNotificationsTickRoute
  '/api/public/s/$shortCode': typeof ApiPublicSShortCodeRoute
  '/api/public/scan/interest': typeof ApiPublicScanInterestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/intelligence': typeof AuthenticatedIntelligenceRoute
  '/_authenticated/intent': typeof AuthenticatedIntentRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRouteWithChildren
  '/_authenticated/products': typeof AuthenticatedProductsRouteWithChildren
  '/_authenticated/qr-tags': typeof AuthenticatedQrTagsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/stores': typeof AuthenticatedStoresRoute
  '/n/$messageId': typeof NMessageIdRoute
  '/scan/$shortCode': typeof ScanShortCodeRoute
  '/_authenticated/notifications/$campaignId': typeof AuthenticatedNotificationsCampaignIdRoute
  '/_authenticated/notifications/new': typeof AuthenticatedNotificationsNewRoute
  '/_authenticated/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/_authenticated/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/api/public/hooks/intent-tick': typeof ApiPublicHooksIntentTickRoute
  '/api/public/hooks/notifications-tick': typeof ApiPublicHooksNotificationsTickRoute
  '/api/public/s/$shortCode': typeof ApiPublicSShortCodeRoute
  '/api/public/scan/interest': typeof ApiPublicScanInterestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/analytics'
    | '/customers'
    | '/dashboard'
    | '/inbox'
    | '/intelligence'
    | '/intent'
    | '/notifications'
    | '/products'
    | '/qr-tags'
    | '/settings'
    | '/staff'
    | '/stores'
    | '/n/$messageId'
    | '/scan/$shortCode'
    | '/notifications/$campaignId'
    | '/notifications/new'
    | '/products/$productId'
    | '/notifications/'
    | '/products/'
    | '/api/public/hooks/intent-tick'
    | '/api/public/hooks/notifications-tick'
    | '/api/public/s/$shortCode'
    | '/api/public/scan/interest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/analytics'
    | '/customers'
    | '/dashboard'
    | '/inbox'
    | '/intelligence'
    | '/intent'
    | '/qr-tags'
    | '/settings'
    | '/staff'
    | '/stores'
    | '/n/$messageId'
    | '/scan/$shortCode'
    | '/notifications/$campaignId'
    | '/notifications/new'
    | '/products/$productId'
    | '/notifications'
    | '/products'
    | '/api/public/hooks/intent-tick'
    | '/api/public/hooks/notifications-tick'
    | '/api/public/s/$shortCode'
    | '/api/public/scan/interest'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/_authenticated/analytics'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/inbox'
    | '/_authenticated/intelligence'
    | '/_authenticated/intent'
    | '/_authenticated/notifications'
    | '/_authenticated/products'
    | '/_authenticated/qr-tags'
    | '/_authenticated/settings'
    | '/_authenticated/staff'
    | '/_authenticated/stores'
    | '/n/$messageId'
    | '/scan/$shortCode'
    | '/_authenticated/notifications/$campaignId'
    | '/_authenticated/notifications/new'
    | '/_authenticated/products/$productId'
    | '/_authenticated/notifications/'
    | '/_authenticated/products/'
    | '/api/public/hooks/intent-tick'
    | '/api/public/hooks/notifications-tick'
    | '/api/public/s/$shortCode'
    | '/api/public/scan/interest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  NMessageIdRoute: typeof NMessageIdRoute
  ScanShortCodeRoute: typeof ScanShortCodeRoute
  ApiPublicHooksIntentTickRoute: typeof ApiPublicHooksIntentTickRoute
  ApiPublicHooksNotificationsTickRoute: typeof ApiPublicHooksNotificationsTickRoute
  ApiPublicSShortCodeRoute: typeof ApiPublicSShortCodeRoute
  ApiPublicScanInterestRoute: typeof ApiPublicScanInterestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/$shortCode': {
      id: '/scan/$shortCode'
      path: '/scan/$shortCode'
      fullPath: '/scan/$shortCode'
      preLoaderRoute: typeof ScanShortCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/n/$messageId': {
      id: '/n/$messageId'
      path: '/n/$messageId'
      fullPath: '/n/$messageId'
      preLoaderRoute: typeof NMessageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/stores': {
      id: '/_authenticated/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof AuthenticatedStoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qr-tags': {
      id: '/_authenticated/qr-tags'
      path: '/qr-tags'
      fullPath: '/qr-tags'
      preLoaderRoute: typeof AuthenticatedQrTagsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intent': {
      id: '/_authenticated/intent'
      path: '/intent'
      fullPath: '/intent'
      preLoaderRoute: typeof AuthenticatedIntentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intelligence': {
      id: '/_authenticated/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof AuthenticatedIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedProductsRoute
    }
    '/_authenticated/notifications/': {
      id: '/_authenticated/notifications/'
      path: '/'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AuthenticatedNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedNotificationsRoute
    }
    '/_authenticated/products/$productId': {
      id: '/_authenticated/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AuthenticatedProductsProductIdRouteImport
      parentRoute: typeof AuthenticatedProductsRoute
    }
    '/_authenticated/notifications/new': {
      id: '/_authenticated/notifications/new'
      path: '/new'
      fullPath: '/notifications/new'
      preLoaderRoute: typeof AuthenticatedNotificationsNewRouteImport
      parentRoute: typeof AuthenticatedNotificationsRoute
    }
    '/_authenticated/notifications/$campaignId': {
      id: '/_authenticated/notifications/$campaignId'
      path: '/$campaignId'
      fullPath: '/notifications/$campaignId'
      preLoaderRoute: typeof AuthenticatedNotificationsCampaignIdRouteImport
      parentRoute: typeof AuthenticatedNotificationsRoute
    }
    '/api/public/scan/interest': {
      id: '/api/public/scan/interest'
      path: '/api/public/scan/interest'
      fullPath: '/api/public/scan/interest'
      preLoaderRoute: typeof ApiPublicScanInterestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/s/$shortCode': {
      id: '/api/public/s/$shortCode'
      path: '/api/public/s/$shortCode'
      fullPath: '/api/public/s/$shortCode'
      preLoaderRoute: typeof ApiPublicSShortCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/notifications-tick': {
      id: '/api/public/hooks/notifications-tick'
      path: '/api/public/hooks/notifications-tick'
      fullPath: '/api/public/hooks/notifications-tick'
      preLoaderRoute: typeof ApiPublicHooksNotificationsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/intent-tick': {
      id: '/api/public/hooks/intent-tick'
      path: '/api/public/hooks/intent-tick'
      fullPath: '/api/public/hooks/intent-tick'
      preLoaderRoute: typeof ApiPublicHooksIntentTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedNotificationsRouteChildren {
  AuthenticatedNotificationsCampaignIdRoute: typeof AuthenticatedNotificationsCampaignIdRoute
  AuthenticatedNotificationsNewRoute: typeof AuthenticatedNotificationsNewRoute
  AuthenticatedNotificationsIndexRoute: typeof AuthenticatedNotificationsIndexRoute
}

const AuthenticatedNotificationsRouteChildren: AuthenticatedNotificationsRouteChildren =
  {
    AuthenticatedNotificationsCampaignIdRoute:
      AuthenticatedNotificationsCampaignIdRoute,
    AuthenticatedNotificationsNewRoute: AuthenticatedNotificationsNewRoute,
    AuthenticatedNotificationsIndexRoute: AuthenticatedNotificationsIndexRoute,
  }

const AuthenticatedNotificationsRouteWithChildren =
  AuthenticatedNotificationsRoute._addFileChildren(
    AuthenticatedNotificationsRouteChildren,
  )

interface AuthenticatedProductsRouteChildren {
  AuthenticatedProductsProductIdRoute: typeof AuthenticatedProductsProductIdRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
}

const AuthenticatedProductsRouteChildren: AuthenticatedProductsRouteChildren = {
  AuthenticatedProductsProductIdRoute: AuthenticatedProductsProductIdRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
}

const AuthenticatedProductsRouteWithChildren =
  AuthenticatedProductsRoute._addFileChildren(
    AuthenticatedProductsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedIntelligenceRoute: typeof AuthenticatedIntelligenceRoute
  AuthenticatedIntentRoute: typeof AuthenticatedIntentRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRouteWithChildren
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRouteWithChildren
  AuthenticatedQrTagsRoute: typeof AuthenticatedQrTagsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedStoresRoute: typeof AuthenticatedStoresRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedIntelligenceRoute: AuthenticatedIntelligenceRoute,
  AuthenticatedIntentRoute: AuthenticatedIntentRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRouteWithChildren,
  AuthenticatedProductsRoute: AuthenticatedProductsRouteWithChildren,
  AuthenticatedQrTagsRoute: AuthenticatedQrTagsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedStoresRoute: AuthenticatedStoresRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  NMessageIdRoute: NMessageIdRoute,
  ScanShortCodeRoute: ScanShortCodeRoute,
  ApiPublicHooksIntentTickRoute: ApiPublicHooksIntentTickRoute,
  ApiPublicHooksNotificationsTickRoute: ApiPublicHooksNotificationsTickRoute,
  ApiPublicSShortCodeRoute: ApiPublicSShortCodeRoute,
  ApiPublicScanInterestRoute: ApiPublicScanInterestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
