/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScanShortCodeRouteImport } from './routes/scan.$shortCode'
import { Route as NMessageIdRouteImport } from './routes/n.$messageId'
import { Route as AuthenticatedWatchlistsRouteImport } from './routes/_authenticated/watchlists'
import { Route as AuthenticatedUpgradeRouteImport } from './routes/_authenticated/upgrade'
import { Route as AuthenticatedStoresRouteImport } from './routes/_authenticated/stores'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRoiRouteImport } from './routes/_authenticated/roi'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedIntentRouteImport } from './routes/_authenticated/intent'
import { Route as AuthenticatedIntelligenceRouteImport } from './routes/_authenticated/intelligence'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated/inbox'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products.index'
import { Route as AuthenticatedProductsCompareRouteImport } from './routes/_authenticated/products.compare'
import { Route as AuthenticatedProductsProductIdRouteImport } from './routes/_authenticated/products.$productId'
import { Route as AuthenticatedOrganisationRolesRouteImport } from './routes/_authenticated/organisation.roles'
import { Route as AuthenticatedIntelligenceTrendsRouteImport } from './routes/_authenticated/intelligence.trends'
import { Route as AuthenticatedIntelligenceIntentRouteImport } from './routes/_authenticated/intelligence.intent'
import { Route as AuthenticatedIntelligenceInsightsRouteImport } from './routes/_authenticated/intelligence.insights'
import { Route as AuthenticatedIntelligenceForecastingRouteImport } from './routes/_authenticated/intelligence.forecasting'
import { Route as AuthenticatedCustomersExportRouteImport } from './routes/_authenticated/customers.export'
import { Route as AuthenticatedCustomersConversationsRouteImport } from './routes/_authenticated/customers.conversations'
import { Route as AuthenticatedCommerceRoiRouteImport } from './routes/_authenticated/commerce.roi'
import { Route as AuthenticatedCommercePricingRouteImport } from './routes/_authenticated/commerce.pricing'
import { Route as AuthenticatedCommerceFunnelRouteImport } from './routes/_authenticated/commerce.funnel'
import { Route as AuthenticatedAnalyticsReportsRouteImport } from './routes/_authenticated/analytics.reports'
import { Route as AuthenticatedAnalyticsHistoryRouteImport } from './routes/_authenticated/analytics.history'
import { Route as ApiPublicWebhooksTwilioInboundRouteImport } from './routes/api/public/webhooks/twilio-inbound'
import { Route as ApiPublicWebhooksPaypalRouteImport } from './routes/api/public/webhooks/paypal'
import { Route as ApiPublicWebhooksPayfastItnRouteImport } from './routes/api/public/webhooks/payfast-itn'
import { Route as ApiPublicScanInterestRouteImport } from './routes/api/public/scan.interest'
import { Route as ApiPublicSShortCodeRouteImport } from './routes/api/public/s.$shortCode'
import { Route as ApiPublicHooksNotificationsTickRouteImport } from './routes/api/public/hooks.notifications-tick'
import { Route as ApiPublicHooksIntentTickRouteImport } from './routes/api/public/hooks.intent-tick'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanShortCodeRoute = ScanShortCodeRouteImport.update({
  id: '/scan/$shortCode',
  path: '/scan/$shortCode',
  getParentRoute: () => rootRouteImport,
} as any)
const NMessageIdRoute = NMessageIdRouteImport.update({
  id: '/n/$messageId',
  path: '/n/$messageId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWatchlistsRoute = AuthenticatedWatchlistsRouteImport.update({
  id: '/watchlists',
  path: '/watchlists',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUpgradeRoute = AuthenticatedUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStoresRoute = AuthenticatedStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoiRoute = AuthenticatedRoiRouteImport.update({
  id: '/roi',
  path: '/roi',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntentRoute = AuthenticatedIntentRouteImport.update({
  id: '/intent',
  path: '/intent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntelligenceRoute =
  AuthenticatedIntelligenceRouteImport.update({
    id: '/intelligence',
    path: '/intelligence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProductsRoute,
  } as any)
const AuthenticatedProductsCompareRoute =
  AuthenticatedProductsCompareRouteImport.update({
    id: '/compare',
    path: '/compare',
    getParentRoute: () => AuthenticatedProductsRoute,
  } as any)
const AuthenticatedProductsProductIdRoute =
  AuthenticatedProductsProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => AuthenticatedProductsRoute,
  } as any)
const AuthenticatedOrganisationRolesRoute =
  AuthenticatedOrganisationRolesRouteImport.update({
    id: '/organisation/roles',
    path: '/organisation/roles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIntelligenceTrendsRoute =
  AuthenticatedIntelligenceTrendsRouteImport.update({
    id: '/trends',
    path: '/trends',
    getParentRoute: () => AuthenticatedIntelligenceRoute,
  } as any)
const AuthenticatedIntelligenceIntentRoute =
  AuthenticatedIntelligenceIntentRouteImport.update({
    id: '/intent',
    path: '/intent',
    getParentRoute: () => AuthenticatedIntelligenceRoute,
  } as any)
const AuthenticatedIntelligenceInsightsRoute =
  AuthenticatedIntelligenceInsightsRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () => AuthenticatedIntelligenceRoute,
  } as any)
const AuthenticatedIntelligenceForecastingRoute =
  AuthenticatedIntelligenceForecastingRouteImport.update({
    id: '/forecasting',
    path: '/forecasting',
    getParentRoute: () => AuthenticatedIntelligenceRoute,
  } as any)
const AuthenticatedCustomersExportRoute =
  AuthenticatedCustomersExportRouteImport.update({
    id: '/export',
    path: '/export',
    getParentRoute: () => AuthenticatedCustomersRoute,
  } as any)
const AuthenticatedCustomersConversationsRoute =
  AuthenticatedCustomersConversationsRouteImport.update({
    id: '/conversations',
    path: '/conversations',
    getParentRoute: () => AuthenticatedCustomersRoute,
  } as any)
const AuthenticatedCommerceRoiRoute =
  AuthenticatedCommerceRoiRouteImport.update({
    id: '/commerce/roi',
    path: '/commerce/roi',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommercePricingRoute =
  AuthenticatedCommercePricingRouteImport.update({
    id: '/commerce/pricing',
    path: '/commerce/pricing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommerceFunnelRoute =
  AuthenticatedCommerceFunnelRouteImport.update({
    id: '/commerce/funnel',
    path: '/commerce/funnel',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsReportsRoute =
  AuthenticatedAnalyticsReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAnalyticsRoute,
  } as any)
const AuthenticatedAnalyticsHistoryRoute =
  AuthenticatedAnalyticsHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedAnalyticsRoute,
  } as any)
const ApiPublicWebhooksTwilioInboundRoute =
  ApiPublicWebhooksTwilioInboundRouteImport.update({
    id: '/api/public/webhooks/twilio-inbound',
    path: '/api/public/webhooks/twilio-inbound',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksPaypalRoute = ApiPublicWebhooksPaypalRouteImport.update({
  id: '/api/public/webhooks/paypal',
  path: '/api/public/webhooks/paypal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksPayfastItnRoute =
  ApiPublicWebhooksPayfastItnRouteImport.update({
    id: '/api/public/webhooks/payfast-itn',
    path: '/api/public/webhooks/payfast-itn',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicScanInterestRoute = ApiPublicScanInterestRouteImport.update({
  id: '/api/public/scan/interest',
  path: '/api/public/scan/interest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSShortCodeRoute = ApiPublicSShortCodeRouteImport.update({
  id: '/api/public/s/$shortCode',
  path: '/api/public/s/$shortCode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksNotificationsTickRoute =
  ApiPublicHooksNotificationsTickRouteImport.update({
    id: '/api/public/hooks/notifications-tick',
    path: '/api/public/hooks/notifications-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksIntentTickRoute =
  ApiPublicHooksIntentTickRouteImport.update({
    id: '/api/public/hooks/intent-tick',
    path: '/api/public/hooks/intent-tick',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AuthenticatedAnalyticsRouteWithChildren
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/intelligence': typeof AuthenticatedIntelligenceRouteWithChildren
  '/intent': typeof AuthenticatedIntentRoute
  '/products': typeof AuthenticatedProductsRouteWithChildren
  '/roi': typeof AuthenticatedRoiRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/stores': typeof AuthenticatedStoresRoute
  '/upgrade': typeof AuthenticatedUpgradeRoute
  '/watchlists': typeof AuthenticatedWatchlistsRoute
  '/n/$messageId': typeof NMessageIdRoute
  '/scan/$shortCode': typeof ScanShortCodeRoute
  '/analytics/history': typeof AuthenticatedAnalyticsHistoryRoute
  '/analytics/reports': typeof AuthenticatedAnalyticsReportsRoute
  '/commerce/funnel': typeof AuthenticatedCommerceFunnelRoute
  '/commerce/pricing': typeof AuthenticatedCommercePricingRoute
  '/commerce/roi': typeof AuthenticatedCommerceRoiRoute
  '/customers/conversations': typeof AuthenticatedCustomersConversationsRoute
  '/customers/export': typeof AuthenticatedCustomersExportRoute
  '/intelligence/forecasting': typeof AuthenticatedIntelligenceForecastingRoute
  '/intelligence/insights': typeof AuthenticatedIntelligenceInsightsRoute
  '/intelligence/intent': typeof AuthenticatedIntelligenceIntentRoute
  '/intelligence/trends': typeof AuthenticatedIntelligenceTrendsRoute
  '/organisation/roles': typeof AuthenticatedOrganisationRolesRoute
  '/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/products/compare': typeof AuthenticatedProductsCompareRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
  '/api/public/hooks/intent-tick': typeof ApiPublicHooksIntentTickRoute
  '/api/public/hooks/notifications-tick': typeof ApiPublicHooksNotificationsTickRoute
  '/api/public/s/$shortCode': typeof ApiPublicSShortCodeRoute
  '/api/public/scan/interest': typeof ApiPublicScanInterestRoute
  '/api/public/webhooks/payfast-itn': typeof ApiPublicWebhooksPayfastItnRoute
  '/api/public/webhooks/paypal': typeof ApiPublicWebhooksPaypalRoute
  '/api/public/webhooks/twilio-inbound': typeof ApiPublicWebhooksTwilioInboundRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AuthenticatedAnalyticsRouteWithChildren
  '/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/intelligence': typeof AuthenticatedIntelligenceRouteWithChildren
  '/intent': typeof AuthenticatedIntentRoute
  '/roi': typeof AuthenticatedRoiRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/stores': typeof AuthenticatedStoresRoute
  '/upgrade': typeof AuthenticatedUpgradeRoute
  '/watchlists': typeof AuthenticatedWatchlistsRoute
  '/n/$messageId': typeof NMessageIdRoute
  '/scan/$shortCode': typeof ScanShortCodeRoute
  '/analytics/history': typeof AuthenticatedAnalyticsHistoryRoute
  '/analytics/reports': typeof AuthenticatedAnalyticsReportsRoute
  '/commerce/funnel': typeof AuthenticatedCommerceFunnelRoute
  '/commerce/pricing': typeof AuthenticatedCommercePricingRoute
  '/commerce/roi': typeof AuthenticatedCommerceRoiRoute
  '/customers/conversations': typeof AuthenticatedCustomersConversationsRoute
  '/customers/export': typeof AuthenticatedCustomersExportRoute
  '/intelligence/forecasting': typeof AuthenticatedIntelligenceForecastingRoute
  '/intelligence/insights': typeof AuthenticatedIntelligenceInsightsRoute
  '/intelligence/intent': typeof AuthenticatedIntelligenceIntentRoute
  '/intelligence/trends': typeof AuthenticatedIntelligenceTrendsRoute
  '/organisation/roles': typeof AuthenticatedOrganisationRolesRoute
  '/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/products/compare': typeof AuthenticatedProductsCompareRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/api/public/hooks/intent-tick': typeof ApiPublicHooksIntentTickRoute
  '/api/public/hooks/notifications-tick': typeof ApiPublicHooksNotificationsTickRoute
  '/api/public/s/$shortCode': typeof ApiPublicSShortCodeRoute
  '/api/public/scan/interest': typeof ApiPublicScanInterestRoute
  '/api/public/webhooks/payfast-itn': typeof ApiPublicWebhooksPayfastItnRoute
  '/api/public/webhooks/paypal': typeof ApiPublicWebhooksPaypalRoute
  '/api/public/webhooks/twilio-inbound': typeof ApiPublicWebhooksTwilioInboundRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRouteWithChildren
  '/_authenticated/customers': typeof AuthenticatedCustomersRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/intelligence': typeof AuthenticatedIntelligenceRouteWithChildren
  '/_authenticated/intent': typeof AuthenticatedIntentRoute
  '/_authenticated/products': typeof AuthenticatedProductsRouteWithChildren
  '/_authenticated/roi': typeof AuthenticatedRoiRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/stores': typeof AuthenticatedStoresRoute
  '/_authenticated/upgrade': typeof AuthenticatedUpgradeRoute
  '/_authenticated/watchlists': typeof AuthenticatedWatchlistsRoute
  '/n/$messageId': typeof NMessageIdRoute
  '/scan/$shortCode': typeof ScanShortCodeRoute
  '/_authenticated/analytics/history': typeof AuthenticatedAnalyticsHistoryRoute
  '/_authenticated/analytics/reports': typeof AuthenticatedAnalyticsReportsRoute
  '/_authenticated/commerce/funnel': typeof AuthenticatedCommerceFunnelRoute
  '/_authenticated/commerce/pricing': typeof AuthenticatedCommercePricingRoute
  '/_authenticated/commerce/roi': typeof AuthenticatedCommerceRoiRoute
  '/_authenticated/customers/conversations': typeof AuthenticatedCustomersConversationsRoute
  '/_authenticated/customers/export': typeof AuthenticatedCustomersExportRoute
  '/_authenticated/intelligence/forecasting': typeof AuthenticatedIntelligenceForecastingRoute
  '/_authenticated/intelligence/insights': typeof AuthenticatedIntelligenceInsightsRoute
  '/_authenticated/intelligence/intent': typeof AuthenticatedIntelligenceIntentRoute
  '/_authenticated/intelligence/trends': typeof AuthenticatedIntelligenceTrendsRoute
  '/_authenticated/organisation/roles': typeof AuthenticatedOrganisationRolesRoute
  '/_authenticated/products/$productId': typeof AuthenticatedProductsProductIdRoute
  '/_authenticated/products/compare': typeof AuthenticatedProductsCompareRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/api/public/hooks/intent-tick': typeof ApiPublicHooksIntentTickRoute
  '/api/public/hooks/notifications-tick': typeof ApiPublicHooksNotificationsTickRoute
  '/api/public/s/$shortCode': typeof ApiPublicSShortCodeRoute
  '/api/public/scan/interest': typeof ApiPublicScanInterestRoute
  '/api/public/webhooks/payfast-itn': typeof ApiPublicWebhooksPayfastItnRoute
  '/api/public/webhooks/paypal': typeof ApiPublicWebhooksPaypalRoute
  '/api/public/webhooks/twilio-inbound': typeof ApiPublicWebhooksTwilioInboundRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/analytics'
    | '/customers'
    | '/dashboard'
    | '/inbox'
    | '/intelligence'
    | '/intent'
    | '/products'
    | '/roi'
    | '/settings'
    | '/staff'
    | '/stores'
    | '/upgrade'
    | '/watchlists'
    | '/n/$messageId'
    | '/scan/$shortCode'
    | '/analytics/history'
    | '/analytics/reports'
    | '/commerce/funnel'
    | '/commerce/pricing'
    | '/commerce/roi'
    | '/customers/conversations'
    | '/customers/export'
    | '/intelligence/forecasting'
    | '/intelligence/insights'
    | '/intelligence/intent'
    | '/intelligence/trends'
    | '/organisation/roles'
    | '/products/$productId'
    | '/products/compare'
    | '/products/'
    | '/api/public/hooks/intent-tick'
    | '/api/public/hooks/notifications-tick'
    | '/api/public/s/$shortCode'
    | '/api/public/scan/interest'
    | '/api/public/webhooks/payfast-itn'
    | '/api/public/webhooks/paypal'
    | '/api/public/webhooks/twilio-inbound'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/analytics'
    | '/customers'
    | '/dashboard'
    | '/inbox'
    | '/intelligence'
    | '/intent'
    | '/roi'
    | '/settings'
    | '/staff'
    | '/stores'
    | '/upgrade'
    | '/watchlists'
    | '/n/$messageId'
    | '/scan/$shortCode'
    | '/analytics/history'
    | '/analytics/reports'
    | '/commerce/funnel'
    | '/commerce/pricing'
    | '/commerce/roi'
    | '/customers/conversations'
    | '/customers/export'
    | '/intelligence/forecasting'
    | '/intelligence/insights'
    | '/intelligence/intent'
    | '/intelligence/trends'
    | '/organisation/roles'
    | '/products/$productId'
    | '/products/compare'
    | '/products'
    | '/api/public/hooks/intent-tick'
    | '/api/public/hooks/notifications-tick'
    | '/api/public/s/$shortCode'
    | '/api/public/scan/interest'
    | '/api/public/webhooks/payfast-itn'
    | '/api/public/webhooks/paypal'
    | '/api/public/webhooks/twilio-inbound'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/_authenticated/analytics'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/inbox'
    | '/_authenticated/intelligence'
    | '/_authenticated/intent'
    | '/_authenticated/products'
    | '/_authenticated/roi'
    | '/_authenticated/settings'
    | '/_authenticated/staff'
    | '/_authenticated/stores'
    | '/_authenticated/upgrade'
    | '/_authenticated/watchlists'
    | '/n/$messageId'
    | '/scan/$shortCode'
    | '/_authenticated/analytics/history'
    | '/_authenticated/analytics/reports'
    | '/_authenticated/commerce/funnel'
    | '/_authenticated/commerce/pricing'
    | '/_authenticated/commerce/roi'
    | '/_authenticated/customers/conversations'
    | '/_authenticated/customers/export'
    | '/_authenticated/intelligence/forecasting'
    | '/_authenticated/intelligence/insights'
    | '/_authenticated/intelligence/intent'
    | '/_authenticated/intelligence/trends'
    | '/_authenticated/organisation/roles'
    | '/_authenticated/products/$productId'
    | '/_authenticated/products/compare'
    | '/_authenticated/products/'
    | '/api/public/hooks/intent-tick'
    | '/api/public/hooks/notifications-tick'
    | '/api/public/s/$shortCode'
    | '/api/public/scan/interest'
    | '/api/public/webhooks/payfast-itn'
    | '/api/public/webhooks/paypal'
    | '/api/public/webhooks/twilio-inbound'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  NMessageIdRoute: typeof NMessageIdRoute
  ScanShortCodeRoute: typeof ScanShortCodeRoute
  ApiPublicHooksIntentTickRoute: typeof ApiPublicHooksIntentTickRoute
  ApiPublicHooksNotificationsTickRoute: typeof ApiPublicHooksNotificationsTickRoute
  ApiPublicSShortCodeRoute: typeof ApiPublicSShortCodeRoute
  ApiPublicScanInterestRoute: typeof ApiPublicScanInterestRoute
  ApiPublicWebhooksPayfastItnRoute: typeof ApiPublicWebhooksPayfastItnRoute
  ApiPublicWebhooksPaypalRoute: typeof ApiPublicWebhooksPaypalRoute
  ApiPublicWebhooksTwilioInboundRoute: typeof ApiPublicWebhooksTwilioInboundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/$shortCode': {
      id: '/scan/$shortCode'
      path: '/scan/$shortCode'
      fullPath: '/scan/$shortCode'
      preLoaderRoute: typeof ScanShortCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/n/$messageId': {
      id: '/n/$messageId'
      path: '/n/$messageId'
      fullPath: '/n/$messageId'
      preLoaderRoute: typeof NMessageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/watchlists': {
      id: '/_authenticated/watchlists'
      path: '/watchlists'
      fullPath: '/watchlists'
      preLoaderRoute: typeof AuthenticatedWatchlistsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/upgrade': {
      id: '/_authenticated/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof AuthenticatedUpgradeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stores': {
      id: '/_authenticated/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof AuthenticatedStoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roi': {
      id: '/_authenticated/roi'
      path: '/roi'
      fullPath: '/roi'
      preLoaderRoute: typeof AuthenticatedRoiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intent': {
      id: '/_authenticated/intent'
      path: '/intent'
      fullPath: '/intent'
      preLoaderRoute: typeof AuthenticatedIntentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intelligence': {
      id: '/_authenticated/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof AuthenticatedIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedProductsRoute
    }
    '/_authenticated/products/compare': {
      id: '/_authenticated/products/compare'
      path: '/compare'
      fullPath: '/products/compare'
      preLoaderRoute: typeof AuthenticatedProductsCompareRouteImport
      parentRoute: typeof AuthenticatedProductsRoute
    }
    '/_authenticated/products/$productId': {
      id: '/_authenticated/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AuthenticatedProductsProductIdRouteImport
      parentRoute: typeof AuthenticatedProductsRoute
    }
    '/_authenticated/organisation/roles': {
      id: '/_authenticated/organisation/roles'
      path: '/organisation/roles'
      fullPath: '/organisation/roles'
      preLoaderRoute: typeof AuthenticatedOrganisationRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intelligence/trends': {
      id: '/_authenticated/intelligence/trends'
      path: '/trends'
      fullPath: '/intelligence/trends'
      preLoaderRoute: typeof AuthenticatedIntelligenceTrendsRouteImport
      parentRoute: typeof AuthenticatedIntelligenceRoute
    }
    '/_authenticated/intelligence/intent': {
      id: '/_authenticated/intelligence/intent'
      path: '/intent'
      fullPath: '/intelligence/intent'
      preLoaderRoute: typeof AuthenticatedIntelligenceIntentRouteImport
      parentRoute: typeof AuthenticatedIntelligenceRoute
    }
    '/_authenticated/intelligence/insights': {
      id: '/_authenticated/intelligence/insights'
      path: '/insights'
      fullPath: '/intelligence/insights'
      preLoaderRoute: typeof AuthenticatedIntelligenceInsightsRouteImport
      parentRoute: typeof AuthenticatedIntelligenceRoute
    }
    '/_authenticated/intelligence/forecasting': {
      id: '/_authenticated/intelligence/forecasting'
      path: '/forecasting'
      fullPath: '/intelligence/forecasting'
      preLoaderRoute: typeof AuthenticatedIntelligenceForecastingRouteImport
      parentRoute: typeof AuthenticatedIntelligenceRoute
    }
    '/_authenticated/customers/export': {
      id: '/_authenticated/customers/export'
      path: '/export'
      fullPath: '/customers/export'
      preLoaderRoute: typeof AuthenticatedCustomersExportRouteImport
      parentRoute: typeof AuthenticatedCustomersRoute
    }
    '/_authenticated/customers/conversations': {
      id: '/_authenticated/customers/conversations'
      path: '/conversations'
      fullPath: '/customers/conversations'
      preLoaderRoute: typeof AuthenticatedCustomersConversationsRouteImport
      parentRoute: typeof AuthenticatedCustomersRoute
    }
    '/_authenticated/commerce/roi': {
      id: '/_authenticated/commerce/roi'
      path: '/commerce/roi'
      fullPath: '/commerce/roi'
      preLoaderRoute: typeof AuthenticatedCommerceRoiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commerce/pricing': {
      id: '/_authenticated/commerce/pricing'
      path: '/commerce/pricing'
      fullPath: '/commerce/pricing'
      preLoaderRoute: typeof AuthenticatedCommercePricingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commerce/funnel': {
      id: '/_authenticated/commerce/funnel'
      path: '/commerce/funnel'
      fullPath: '/commerce/funnel'
      preLoaderRoute: typeof AuthenticatedCommerceFunnelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/reports': {
      id: '/_authenticated/analytics/reports'
      path: '/reports'
      fullPath: '/analytics/reports'
      preLoaderRoute: typeof AuthenticatedAnalyticsReportsRouteImport
      parentRoute: typeof AuthenticatedAnalyticsRoute
    }
    '/_authenticated/analytics/history': {
      id: '/_authenticated/analytics/history'
      path: '/history'
      fullPath: '/analytics/history'
      preLoaderRoute: typeof AuthenticatedAnalyticsHistoryRouteImport
      parentRoute: typeof AuthenticatedAnalyticsRoute
    }
    '/api/public/webhooks/twilio-inbound': {
      id: '/api/public/webhooks/twilio-inbound'
      path: '/api/public/webhooks/twilio-inbound'
      fullPath: '/api/public/webhooks/twilio-inbound'
      preLoaderRoute: typeof ApiPublicWebhooksTwilioInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/paypal': {
      id: '/api/public/webhooks/paypal'
      path: '/api/public/webhooks/paypal'
      fullPath: '/api/public/webhooks/paypal'
      preLoaderRoute: typeof ApiPublicWebhooksPaypalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/payfast-itn': {
      id: '/api/public/webhooks/payfast-itn'
      path: '/api/public/webhooks/payfast-itn'
      fullPath: '/api/public/webhooks/payfast-itn'
      preLoaderRoute: typeof ApiPublicWebhooksPayfastItnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scan/interest': {
      id: '/api/public/scan/interest'
      path: '/api/public/scan/interest'
      fullPath: '/api/public/scan/interest'
      preLoaderRoute: typeof ApiPublicScanInterestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/s/$shortCode': {
      id: '/api/public/s/$shortCode'
      path: '/api/public/s/$shortCode'
      fullPath: '/api/public/s/$shortCode'
      preLoaderRoute: typeof ApiPublicSShortCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/notifications-tick': {
      id: '/api/public/hooks/notifications-tick'
      path: '/api/public/hooks/notifications-tick'
      fullPath: '/api/public/hooks/notifications-tick'
      preLoaderRoute: typeof ApiPublicHooksNotificationsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/intent-tick': {
      id: '/api/public/hooks/intent-tick'
      path: '/api/public/hooks/intent-tick'
      fullPath: '/api/public/hooks/intent-tick'
      preLoaderRoute: typeof ApiPublicHooksIntentTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAnalyticsRouteChildren {
  AuthenticatedAnalyticsHistoryRoute: typeof AuthenticatedAnalyticsHistoryRoute
  AuthenticatedAnalyticsReportsRoute: typeof AuthenticatedAnalyticsReportsRoute
}

const AuthenticatedAnalyticsRouteChildren: AuthenticatedAnalyticsRouteChildren =
  {
    AuthenticatedAnalyticsHistoryRoute: AuthenticatedAnalyticsHistoryRoute,
    AuthenticatedAnalyticsReportsRoute: AuthenticatedAnalyticsReportsRoute,
  }

const AuthenticatedAnalyticsRouteWithChildren =
  AuthenticatedAnalyticsRoute._addFileChildren(
    AuthenticatedAnalyticsRouteChildren,
  )

interface AuthenticatedCustomersRouteChildren {
  AuthenticatedCustomersConversationsRoute: typeof AuthenticatedCustomersConversationsRoute
  AuthenticatedCustomersExportRoute: typeof AuthenticatedCustomersExportRoute
}

const AuthenticatedCustomersRouteChildren: AuthenticatedCustomersRouteChildren =
  {
    AuthenticatedCustomersConversationsRoute:
      AuthenticatedCustomersConversationsRoute,
    AuthenticatedCustomersExportRoute: AuthenticatedCustomersExportRoute,
  }

const AuthenticatedCustomersRouteWithChildren =
  AuthenticatedCustomersRoute._addFileChildren(
    AuthenticatedCustomersRouteChildren,
  )

interface AuthenticatedIntelligenceRouteChildren {
  AuthenticatedIntelligenceForecastingRoute: typeof AuthenticatedIntelligenceForecastingRoute
  AuthenticatedIntelligenceInsightsRoute: typeof AuthenticatedIntelligenceInsightsRoute
  AuthenticatedIntelligenceIntentRoute: typeof AuthenticatedIntelligenceIntentRoute
  AuthenticatedIntelligenceTrendsRoute: typeof AuthenticatedIntelligenceTrendsRoute
}

const AuthenticatedIntelligenceRouteChildren: AuthenticatedIntelligenceRouteChildren =
  {
    AuthenticatedIntelligenceForecastingRoute:
      AuthenticatedIntelligenceForecastingRoute,
    AuthenticatedIntelligenceInsightsRoute:
      AuthenticatedIntelligenceInsightsRoute,
    AuthenticatedIntelligenceIntentRoute: AuthenticatedIntelligenceIntentRoute,
    AuthenticatedIntelligenceTrendsRoute: AuthenticatedIntelligenceTrendsRoute,
  }

const AuthenticatedIntelligenceRouteWithChildren =
  AuthenticatedIntelligenceRoute._addFileChildren(
    AuthenticatedIntelligenceRouteChildren,
  )

interface AuthenticatedProductsRouteChildren {
  AuthenticatedProductsProductIdRoute: typeof AuthenticatedProductsProductIdRoute
  AuthenticatedProductsCompareRoute: typeof AuthenticatedProductsCompareRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
}

const AuthenticatedProductsRouteChildren: AuthenticatedProductsRouteChildren = {
  AuthenticatedProductsProductIdRoute: AuthenticatedProductsProductIdRoute,
  AuthenticatedProductsCompareRoute: AuthenticatedProductsCompareRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
}

const AuthenticatedProductsRouteWithChildren =
  AuthenticatedProductsRoute._addFileChildren(
    AuthenticatedProductsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRouteWithChildren
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedIntelligenceRoute: typeof AuthenticatedIntelligenceRouteWithChildren
  AuthenticatedIntentRoute: typeof AuthenticatedIntentRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRouteWithChildren
  AuthenticatedRoiRoute: typeof AuthenticatedRoiRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedStoresRoute: typeof AuthenticatedStoresRoute
  AuthenticatedUpgradeRoute: typeof AuthenticatedUpgradeRoute
  AuthenticatedWatchlistsRoute: typeof AuthenticatedWatchlistsRoute
  AuthenticatedCommerceFunnelRoute: typeof AuthenticatedCommerceFunnelRoute
  AuthenticatedCommercePricingRoute: typeof AuthenticatedCommercePricingRoute
  AuthenticatedCommerceRoiRoute: typeof AuthenticatedCommerceRoiRoute
  AuthenticatedOrganisationRolesRoute: typeof AuthenticatedOrganisationRolesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRouteWithChildren,
  AuthenticatedCustomersRoute: AuthenticatedCustomersRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedIntelligenceRoute: AuthenticatedIntelligenceRouteWithChildren,
  AuthenticatedIntentRoute: AuthenticatedIntentRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRouteWithChildren,
  AuthenticatedRoiRoute: AuthenticatedRoiRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedStoresRoute: AuthenticatedStoresRoute,
  AuthenticatedUpgradeRoute: AuthenticatedUpgradeRoute,
  AuthenticatedWatchlistsRoute: AuthenticatedWatchlistsRoute,
  AuthenticatedCommerceFunnelRoute: AuthenticatedCommerceFunnelRoute,
  AuthenticatedCommercePricingRoute: AuthenticatedCommercePricingRoute,
  AuthenticatedCommerceRoiRoute: AuthenticatedCommerceRoiRoute,
  AuthenticatedOrganisationRolesRoute: AuthenticatedOrganisationRolesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  NMessageIdRoute: NMessageIdRoute,
  ScanShortCodeRoute: ScanShortCodeRoute,
  ApiPublicHooksIntentTickRoute: ApiPublicHooksIntentTickRoute,
  ApiPublicHooksNotificationsTickRoute: ApiPublicHooksNotificationsTickRoute,
  ApiPublicSShortCodeRoute: ApiPublicSShortCodeRoute,
  ApiPublicScanInterestRoute: ApiPublicScanInterestRoute,
  ApiPublicWebhooksPayfastItnRoute: ApiPublicWebhooksPayfastItnRoute,
  ApiPublicWebhooksPaypalRoute: ApiPublicWebhooksPaypalRoute,
  ApiPublicWebhooksTwilioInboundRoute: ApiPublicWebhooksTwilioInboundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
